plugwise/plugwise-beta

custom_components/plugwise-beta/manifest.json
custom_components/plugwise-beta/manifest.json.ha-core
custom_components/plugwise-beta/sensor.py

Diff says it all, using wrong labels meant no gas visibility
Issue https://github.com/plugwise/plugwise-beta/issues/2
Might be merged together with https://github.com/plugwise/Plugwise-Smile/pull/4 - note that both PRs **lack** `setup.py`/`manifest.json` updates.

Fix wrongly labeled meters for gas

---

custom_components/plugwise-beta/__init__.py
custom_components/plugwise-beta/manifest.json

and PNR isn't imported anyway, so should have failed?
See comments in #11

Ensure ConfigEntryNotReady is used like upstream

---

custom_components/plugwise-beta/sensor.py

Either by misjudgement or change in naming we only included non-peak interval measurements. As pointed out by @willsmarthome in #78 this should also be disclosed by our sensors platform.
Leaving the non peak indicated in (for now).
Closing #78

P1 interval

---

custom_components/plugwise-beta/binary_sensor.py
custom_components/plugwise-beta/config_flow.py
custom_components/plugwise-beta/manifest.json

This PR requires Smile v1.2.0!
Changes:
- Same config_flow unique_id when configuring via zeroconf discovery or via manual entry (BREAKING CHANGE)
- Fix config_flow "unique_id = None" for Smile P1 v2 (BREAKING CHANGE)
- Binary_sensor code improvements
- Fix notifications not automatically clearing (introduced in HA Core 0.113?)

One unique_id and improved binary_sensor

---

custom_components/plugwise/.vscode/settings.json
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py

Including #129 as requested by @bouwew 
- Availability (as per #129) handling
- Introduce `ATTR_ENABLED_DEFAULT` and included on the Entity classes
- Rewrite gateway sensoric maps to dictionaries as with stick - superceeding introduced `CUSTOM_ICONS`
- Handle icon only if no DEVICE_CLASS is set (as per Core decision)
- Set `PARALLEL_UPDATES` on `sensor` and `binary_sensor` as first included platforms
- Import more ATTR consts from core
**Silver**
- Yes, using the 'hub' approach and DataUpdateCoordinator to talk to our module
- Yes, dependent on type of hub (e.g. climate devices every minute, DSMR every 10 seconds)
- Yes, handled appropriately
- n/a there is a static password printed on the back of the devices
- n/a local devices
- Per 'hub' using DataUpdateCoordinator
- Per 'hub' using …

Code quality push (for platinum upstream)

---

README.md
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/manifest.json
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py
custom_components/plugwise/usb.py

- USB-Stick
- New: Automatically accepting of joining request of new Plugwise devices if the `Enable newly added entries` system option is turned on (default). A notification will be popup after a new devices is joined.
- Improved: For quicker response switch (relay) requests are handled with priority
- Improved: Dynamically set the refresh interval based on the actual discovered devices with power measurement capabilities
- Improved: Response messages received from Plugwise devices are now validated to their checksums.
- Improved: Using the `device_remove` services will remove the devices from the device registry too.
- Improved: Better handling of timeout issues and reduced communication messages.
- Improved: Corrected log level assignments (debug, info, warning, errors)
- Fixed: …

Update to new API stick 

---

custom_components/plugwise/switch.py

Sorry, I didn't test properly, the new `dhw_comf_mode` switch implementation renames the Auxiliary-device.
With these changes it works on my system.
But, there's one **breaking-change** I've also found: the unique_id of the Switch Groups is changed, this will cause `_2` switches. This only impacts users that have grouped Plugs(Adam) and Circles, Stealths (Stretches), not too many users.
I could work around this but I'd prefer not too as this will add more code.

Fix device naming, add enabled_default

---

.github/workflows/test.yml
.vscode/settings.json
LICENSE
README.md
custom_components/plugwise/config_flow.py
scripts/core-testing.sh
tests/components/plugwise/test_config_flow.py

Add tests from 'plugwise-usb' commits (PR at core)
Quiesce testing some more
Rework 'with p1 as ...' as codefactor found these pylint-confusing
Rework the PlugwiseNode->FakeStick construction of plugwise-usb to inline patching (and follow conformant use of mac vs get_mac_stick)

Add usb testing

---

.bandit
custom_components/plugwise/config_flow.py
scripts/core-testing.sh
tests/components/plugwise/test_config_flow.py

Forementioned (#158 and #160) lines were all about stick (usb), L217 wasn't reachable as per design (user can only select from listed ports or manual) so that part was removed. Added testing part for options while using a stick.
Should result in 100% coverage on config_flow (and therefore for upstreaming)

Complete config_flow coverage

---

.gitignore
.vscode/settings.json
README.md

Remove .vscode settings
Update relevant README parts and introduce the 'my homeassistant' button to encourage using core
@bouwew We should check if we shouldn't bump `hacs.json` to a newer `homeassistant` as well?

Clean-up and improve README

---

custom_components/plugwise/manifest.json
custom_components/plugwise/usb.py
tests/components/plugwise/test_binary_sensor.py
tests/components/plugwise/test_climate.py
tests/components/plugwise/test_init.py
tests/components/plugwise/test_sensor.py
tests/components/plugwise/test_switch.py

This PR will fix issue #174
At Home Assistant version 2021.6 the stored format of "system options" [has changed](https://github.com/home-assistant/core/pull/51347). This PR will check for the HA version and use the proper stored field to retrieve the configured setting for "Enable newly added entities".

Adapt to changed storage format of "system options" in HA 2021.6

---

custom_components/plugwise/switch.py

This faulty code still works with plugwise v0.16.0 but will no longer work with the next planned update, v0.16.1 (see the changes in https://github.com/plugwise/python-plugwise/tree/smile_private)

Fix missed parameter-change

---

.github/workflows/hassfest.yaml
.github/workflows/test.yml
custom_components/plugwise/manifest.json
scripts/core-testing.sh

Change hassfest handling. Basically with the changes in https://github.com/home-assistant/core/blob/13067003cbffa9579d30b213afc6d48edd8a7267/script/hassfest/requirements.py#L111 it is no longer allowed to have anything but package name and version.
Changes modify ha-core testing (i.e. Test-action in Workflow) to just validate the hassfest check on package (basically ignoring it) while still validating hassfest.
The Hassfest-action in Workflow is altered to only do full hasstest against the ha-action when there is a valid package present.
Todo: test against newer PR with test-pypi to ensure it works.

Add hassfest action workaround

---

.github/dependabot.yml
.github/workflows/test.yml
scripts/core-testing.sh

Tiny (cleanup) PR to add dependabot for the build actions and improve on our shell testcode.
Also makes running the test/coverage script easier (handling of ha-core directory)

Add shellcheck and dependabot

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml
.gitignore

Replacing our current `bug_report`-one with the templated/form version, I don't think we can properly preview it and not 'done' yet.
Example: https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml

Form-based bug report

---

README.md
custom_components/plugwise/climate.py
custom_components/plugwise/const.py
custom_components/plugwise/manifest.json
custom_components/plugwise/select.py
custom_components/plugwise/services.yaml
scripts/core-testing.sh

Add active schema/schedule select functionality as requested
Testing this is rather hard, as we'd have to mock the Location id from one place to another. It's possible but will require xml into the conftest.
As long as this is not upstreamed: in core-testing added changing `.coveragerc` accordingly NOT to test the select option.
**BREAKING** in that we choose `schedule` over `schema` and as such renamed the thermostat visible attributes to `available_schedules` and `selected_schedule` accordingly

Schedule service **POTENTIALLY BREAKING**

---

.github/workflows/test.yml
scripts/core-testing.sh

Bumped to python 3.10
Ensure we only use 1 method (i.e. DRY) to test locally and in actions
Removed pylint, use `COMMIT_CHECK=true scripts/core-testing.sh` locally (eventually we should include this in the action to test all requirements for upstreaming
Side-action (not for this PR): we should really isort again :)

Improve testing and DRY between local and github actions

---

README.md
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/entity.py
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
scripts/core-testing.sh
tests/components/plugwise/test_climate.py

Changes:
- Add filtering for input: via the `climate.set_xyz` functions invalid inputs can be provided. Until now these were accepted without providing any feedback for Plugwise
-  Improve generation of the `hvac_modes` list: for Anna: `auto` and `heat` / `heat_cool` (`heat_cool` because heating or cooling is executed automatically), and for Adam: `auto` and `heat` or `auto` and `cool` (because switching between heating and cooling is done manually).
- Replace `.get()`s because they are not a great solution in combination with typing hints.
- Proposal for fixing the not working scan_interval option.

Climate: add extra filtering, improve cooling hvac-modes

---

README.md
custom_components/plugwise/config_flow.py
custom_components/plugwise/manifest.json
custom_components/plugwise/strings.json
custom_components/plugwise/translations/en.json
custom_components/plugwise/translations/nl.json

The updated code saves the provided input for a next attempt, when adding the Plugwise integration fails, due to e.g. a typing error.

Improve config_flow: save user input

---

README.md
scripts/core-testing.sh

Add debug logging on execution of the tests (i.e. when no tests fail, pytest stays silent, effectively not showing any debug output). Usage: i.e. `export DEBUG=something` beforehand or execute `DEBUG= scripts/core-testing`
Cleaned up some of the README that was outdated

Add debug local test

---

custom_components/plugwise/models.py

This fixes the warnings ` sensor.xyz_interval is using state class 'measurement' which is impossible considering device class ('energy') it is using`

Correct device_class and state_classes

---

custom_components/plugwise/usb.py

As instructed by https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

Change async_setup_platforms into async_forward_entry_setups

---

custom_components/plugwise/__init__.py
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/coordinator.py
custom_components/plugwise/diagnostics.py
custom_components/plugwise/gateway.py
custom_components/plugwise/number.py
custom_components/plugwise/select.py
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py

Following https://plugwise.github.io/progress/diff.html
Adding `# pw-beta` tags where appropriate to ease up differences
PR is also meant as a step-up to see if we can carve out a way for the Core Team to decide on embedding USB into the Core Plugwise environment. E.g. making sure the 'mammoth' that is now https://plugwise.github.io/progress/diff.html can be used as an oversight and from that we can chunk PRs in a relative quick pace to ensure we embed USB within a month between releases. As such re-breathing live into Core PR 35713 
Checklist as per [Progress diff core/beta](https://plugwise.github.io/progress/diff.html) beginning of March 2023: (note that all `COORDINATOR` relations are under `coordinator.py` to not re-iterate across all domains)

Core v Beta progress update

---

custom_components/plugwise/models.py

This PR sets the category for Ping and RSSI in/out sensor to diagnostic.

Make ping and rssi for Stick circles category diagnostic

---

.github/workflows/test.yml
.pre-commit-config.yaml
custom_components/plugwise/__init__.py
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/coordinator.py
custom_components/plugwise/diagnostics.py
custom_components/plugwise/number.py
custom_components/plugwise/select.py
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py
pyproject.toml
scripts/core-testing.sh
tests/components/plugwise/conftest.py
tests/components/plugwise/test_binary_sensor.py
tests/components/plugwise/test_climate.py
tests/components/plugwise/test_config_flow.py
tests/components/plugwise/test_diagnostics.py
tests/components/plugwise/test_init.py
tests/components/plugwise/test_number.py
tests/components/plugwise/test_select.py
tests/components/plugwise/test_sensor.py
tests/components/plugwise/test_switch.py

Follow upstream, caveat;
```
+from plugwise.exceptions import PlugwiseError
import voluptuous as vol
from homeassistant.components.switch import DOMAIN as SWITCH_DOMAIN
@@ -10,7 +11,6 @@
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant, ServiceCall, callback
from homeassistant.helpers import device_registry as dr, entity_registry as er
-from plugwise.exceptions import PlugwiseError
```

isort 2 ruff

---

tests/components/plugwise/fixtures/m_anna_heatpump_cooling/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_idle/all_data.json

Fixtures changes from v0.31.8
~~Apparently (again) ordering updates after running core-testing?~~ setting to draft (figure out why ruff pre-commit changes back

Fixture update from module

---

.github/workflows/test.yml
.pre-commit-config.yaml
scripts/core-testing.sh

This will still test the weekly (and regular PR updates) against both branches, if `dev` fails we can still merge (overriding the failed check) without issue, but this will ensure we get triggered to create an [issue](https://github.com/plugwise/plugwise-beta/issues/new/choose) to solve it before the next release hits.

Add branch defaulting suggestions

---

.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
custom_components/plugwise/__init__.py
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/coordinator.py
custom_components/plugwise/entity.py
custom_components/plugwise/manifest.json
custom_components/plugwise/number.py
custom_components/plugwise/select.py
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py
custom_components/plugwise/util.py
pyproject.toml
scripts/core-testing.sh
scripts/python-venv.sh
tests/components/plugwise/conftest.py
tests/components/plugwise/fixtures/p1v4_442_triple/all_data.json
tests/components/plugwise/fixtures/p1v4_442_triple/notifications.json
tests/components/plugwise/test_binary_sensor.py
tests/components/plugwise/test_climate.py
tests/components/plugwise/test_config_flow.py
tests/components/plugwise/test_diagnostics.py
tests/components/plugwise/test_init.py
tests/components/plugwise/test_number.py
tests/components/plugwise/test_select.py
tests/components/plugwise/test_sensor.py
tests/components/plugwise/test_switch.py

All changes:
- Link to [plugwise v0.32.1](https://github.com/plugwise/python-plugwise/releases/tag/v0.32.1)
- Remove python3.9 compatibility: remove/replace all python3.9 references.
- Implement Ruff sorting fixes - tnx @CoMPaTech for achieving the line-up with the Core Plugwise code.
- Update p1v4_442_triple testfixture, adding a Plugwise notification for the Smile P1. Add a related testcase.
- Bump PW-beta to v0.41.2

Link to plugwise v0.32.1, remove py39 compatibility

---

.github/workflows/core_next.yml
.github/workflows/test.yml

Intention would be to run this weekly and (re)create (another) issue when we have a compatibility issue between released HA-Core (i.e. `master`) and upcoming (i.e. `dev`)
Note2self: subscribed to https://github.com/imjohnbo/issue-bot/issues/90 so we can just ignore and/or amend an existing issue instead of (weekly) (re)creating the same issue

Improve warning through issue creation on Core DEV (RC/Beta) commits

---

custom_components/plugwise/coordinator.py
custom_components/plugwise/manifest.json

Fixes for the 2nd try releasing v0.44.0, a follow-up on https://github.com/plugwise/plugwise-beta/pull/515
Device-cleaning is done in `coordinator.py` because there can be more than one Plugwise-gateway in a HA system.
So care must be taken to avoid devices being removed for the other gateway(s) when the `device_registry` is processed for one gateway.
Also, it is planned for the future to extend this function by triggering a reload when new devices are detected.

Fix device_registry clean-up for systems with more than 1 Plugwise Gateway

---

custom_components/plugwise/manifest.json
tests/components/plugwise/fixtures/adam_multiple_devices_per_zone/all_data.json
tests/components/plugwise/fixtures/m_adam_cooling/all_data.json
tests/components/plugwise/fixtures/m_adam_heating/all_data.json
tests/components/plugwise/fixtures/m_adam_jip/all_data.json
tests/components/plugwise/fixtures/stretch_v31/all_data.json
tests/components/plugwise/snapshots/test_diagnostics.ambr

More info:
- The backend-code for actual and legacy Plugwise devices has been separated.
- For actual devices xml-data is now only collected from `/core/domain_objects`.

Implement plugwise v0.37.0

---

CHANGELOG.md
custom_components/plugwise/icons.json
custom_components/plugwise/select.py
custom_components/plugwise/strings.json
custom_components/plugwise/translations/en.json
custom_components/plugwise/translations/nl.json

Also, line up key-naming with Core, now the thermostat-schedule icons are not working.

Add off-icon for thermostat schedules

---

CHANGELOG.md
custom_components/plugwise/__init__.py
custom_components/plugwise/coordinator.py
custom_components/plugwise/manifest.json
custom_components/plugwise/util.py
tests/components/plugwise/test_init.py

All changes:
- Improve code in `coordinator.py`
- Move automatic device removal to `__init__.py`, function to `util.py` and make it work properly so that it functions too when there are more than 1 Plugwise integrations loaded (e.g. Adam plus P1).
- Add `async_remove_config_entry_device()` function, this will allow a user to manually delete a removed Plugwise device.

Improve device-delete related functions

---

CHANGELOG.md
custom_components/plugwise/manifest.json

All changes:
- Bugfix for #620 via plugwise v0.37.3
- Require python 3.12 (as Core 2024.2 already does)
- Link to plugwise v0.37.2 via plugwise v0.37.1
- Replace many recurring text-strings by CONSTANTS.

Collected updates

---

custom_components/plugwise/__init__.py

This fixes only showing the first number of the firmware for (legacy) P1.
Solution for #629

Show full firmware-version

---

CHANGELOG.md
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/button.py
custom_components/plugwise/climate.py
custom_components/plugwise/coordinator.py
custom_components/plugwise/manifest.json
custom_components/plugwise/number.py
custom_components/plugwise/select.py
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py
tests/components/plugwise/test_init.py

All changes:
- In the platform files change to adding only the new devices: all at init, only new at runtime.
- Climate: return debug logging
- Coordinator: improve the detection of added/removed devices using `set()`, optimize code.
- Tests: rename the Tom to avoid the creation of double entities.

Refactor runtime-update/remove related code
