plugwise/plugwise-beta

custom_components/plugwise-beta/sensor.py

Check tariff structure presence

---

custom_components/plugwise-beta/sensor.py

Fix tariff structure presence

---

custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/manifest.json

Accompanying change for `zone_thermo_improve` on both repo's to include radiator valves as thermostats.

Include radiator valves

---

custom_components/plugwise-beta/manifest.json

For https://github.com/plugwise/Plugwise-Smile/pull/8 and https://github.com/plugwise/Plugwise-Smile/issues/6 
Also needs new release to `0.0.51` on releases

Bump version for anna v4 support and legacy improvements

---

custom_components/plugwise-beta/manifest.json

Waiting for travis/pypi on https://github.com/plugwise/Plugwise-Smile/pull/12

Version bump for gateway fix

---

custom_components/plugwise-beta/manifest.json

Version bump for dhw in .55

---

custom_components/plugwise-beta/__init__.py
custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/config_flow.py
custom_components/plugwise-beta/manifest.json
custom_components/plugwise-beta/manifest.json.ha-core
custom_components/plugwise-beta/sensor.py
custom_components/plugwise-beta/water_heater.py

Accompanying https://github.com/plugwise/Plugwise-Smile/pull/18/
As with the mentioned PR the 0.1.1 fix should go first - this is intended as 0.1.2

v0.1.2 Fix LINT issues, correct api public vars, cleanup

---

custom_components/plugwise-beta/sensor.py

Fix thermostat-sensor battery percentage

---

custom_components/plugwise-beta/manifest.json

Add missing get_preset for legacy_anna

Link to Smile 0.1.5

---

custom_components/plugwise-beta/__init__.py
custom_components/plugwise-beta/binary_sensor.py
custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/sensor.py
custom_components/plugwise-beta/switch.py
custom_components/plugwise-beta/water_heater.py

Depends on `remotes/origin/single_master_thermostat` PR #32

Rework device registry

---

custom_components/plugwise-beta/binary_sensor.py
custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/sensor.py
custom_components/plugwise-beta/switch.py
custom_components/plugwise-beta/water_heater.py

Device mapping to "Auxiliary Device" (short Auxiliary)

---

custom_components/plugwise-beta/binary_sensor.py
custom_components/plugwise-beta/sensor.py
custom_components/plugwise-beta/water_heater.py

Phase 3 of `devicenames2` branch. Merging everything into gateway_id
(`switch` and `climate` are excempt as these would never be a gateway device (at least, with current state of the hardware))

Merge heater_central into gateway

---

custom_components/plugwise-beta/__init__.py
custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/config_flow.py

Removed the older pr-branch, but we need this stuff for our own 0.2.x as well to make sure we can easier align with upstream HA
Might not yet be complete (waiting for CI on upstream 33691 to finish)

PR Cleanup

---

README.md
custom_components/plugwise-beta/binary_sensor.py
custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/manifest.json
custom_components/plugwise-beta/manifest.json.ha-core
custom_components/plugwise-beta/sensor.py
custom_components/plugwise-beta/switch.py

Mostly version bump with updates to README and some `black`

Release 0.2.0

---

custom_components/plugwise-beta/climate.py

0.2.0b0 improvements

---

README.md

Before merging add url to specific release page for 0.2.0

Add warning to README to make it more obvious for HACS users

---

custom_components/plugwise-beta/sensor.py

Forgot to scale valve_position

valve_position*100

---

custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/manifest.json

"Solves" #61.
Let's use this PR to collect several proposed changes for a next release.

Show available_schemas only when more than 1

---

custom_components/plugwise-beta/__init__.py
custom_components/plugwise-beta/binary_sensor.py
custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/config_flow.py
custom_components/plugwise-beta/sensor.py
custom_components/plugwise-beta/switch.py
hacs.json

Combined, non-breaking upstream review and 110 compliancy

---

custom_components/plugwise-beta/binary_sensor.py
custom_components/plugwise-beta/climate.py
custom_components/plugwise-beta/config_flow.py
custom_components/plugwise-beta/const.py
custom_components/plugwise-beta/manifest.json
custom_components/plugwise-beta/sensor.py
custom_components/plugwise-beta/switch.py

Review comments 0.111

---

custom_components/plugwise-beta/binary_sensor.py
custom_components/plugwise-beta/sensor.py

This should fix https://github.com/home-assistant/core/issues/38238

Add missing icon-definition

---

custom_components/plugwise/binary_sensor.py
custom_components/plugwise/climate.py
custom_components/plugwise/switch.py

Fix https://github.com/plugwise/plugwise-beta/issues/75

Align unique_ids

---

custom_components/plugwise/__init__.py
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/sensor.py

**Breaking** 0.115 required (UNIT_PERCENTAGE => PERCENTAGE change by Core)
Closing https://github.com/plugwise/plugwise-beta/issues/103

Refit #103

---

custom_components/plugwise/__init__.py
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/manifest.json
custom_components/plugwise/services.yaml
custom_components/plugwise/strings.json
custom_components/plugwise/translations/en.json
custom_components/plugwise/translations/nl.json

- Add a service to delete Plugwise Notification(s) from within HA Core
- Copy the port implementation from Core PR #40017

Add service delete_notification

---

custom_components/plugwise/__init__.py

Remove dual _update_listener def from #110

---

custom_components/plugwise/__init__.py

When migrating from Core to beta

Add the missing username in config-entry

---

custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py

Proof of concept implementation for detecting usernames on discovery, for now assumes stretch if it's not a smile :)

POC: Username detection

---

custom_components/plugwise/const.py

Don't use SIGNAL_STRENGTH_DECIBELS_MILLIWATT from HA

---

custom_components/plugwise/const.py
hacs.json

Revert #135 and set minimal HA version for HACS to 0.117.0

Revert PR135 and set minimal HA to 0.117

---

custom_components/plugwise/binary_sensor.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
custom_components/plugwise/switch.py

Persistent notifications left in (although changed to lower instead of upper in line with core change for keys)

Changes on core for 41473

---

custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
custom_components/plugwise/switch.py

And some small changes/improvements implemented in `gateway.py`.

Implement dhw comfort mode switch

---

tests/components/plugwise/common.py
tests/components/plugwise/conftest.py
tests/components/plugwise/test_binary_sensor.py

Improve by actually enabling instead of patching the code beforehand to default to enabling

Improve enabling and testing binary_sensor

---

.github/workflows/test.yml
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
custom_components/plugwise/usb.py

Implement the latest plugwise update.

Link to plugwise v0.9.4

---

.github/workflows/test.yml
custom_components/plugwise/config_flow.py
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
scripts/core-testing.sh

Hassfest indicates https://developers.home-assistant.io/docs/creating_integration_manifest/#iot-class is now required

hassfest fix

---

custom_components/plugwise/const.py

Fix missing Tom/Floor climate-devices in v0.15.0

Add thermostatic_radiator_valve to MASTER_THERMOSTATS

---

.github/workflows/test.yml
custom_components/plugwise/config_flow.py
custom_components/plugwise/usb.py

This change was for some reason left out in the last PR.

Remaining config_flow clean up

---

custom_components/plugwise/gateway.py

Also replace inline if-else constructs.

Update config_url implementation

---

README.md
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
custom_components/plugwise/translations/en.json
custom_components/plugwise/translations/nl.json

Make homekit an option (i.e. most probably will not be available from core) for beta

Homekit option

---

.github/workflows/test.yml
README.md
custom_components/plugwise/config_flow.py
custom_components/plugwise/manifest.json
custom_components/plugwise/sensor.py
custom_components/plugwise/strings.json
custom_components/plugwise/translations/en.json
custom_components/plugwise/translations/nl.json
tests/components/plugwise/fixtures/adam_multiple_devices_per_zone/all_data.json
tests/components/plugwise/fixtures/anna_heatpump/all_data.json
tests/components/plugwise/test_config_flow.py
tests/components/plugwise/test_diagnostics.py
tests/components/plugwise/test_sensor.py

https://github.com/plugwise/python-plugwise/pull/159

Add module #159 counterparts

---

.gitignore
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/entity.py
custom_components/plugwise/number.py
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py
custom_components/plugwise/usb.py
scripts/core-testing.sh

Part of #265 
can only be merged after the todo-list is complete (otherwise CI will fail)

Force mypy - all pending changes included

---

custom_components/plugwise/binary_sensor.py
tests/components/plugwise/test_binary_sensor.py

PR#281 needs to be merged first! Then the branch needs to be rebased.

Add test for plugwise_notification

---

README.md
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/manifest.json
custom_components/plugwise/strings.json
custom_components/plugwise/translations/en.json
custom_components/plugwise/translations/nl.json
tests/components/plugwise/conftest.py
tests/components/plugwise/fixtures/anna_heatpump_heating/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_cooling/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_idle/all_data.json
tests/components/plugwise/test_climate.py
tests/components/plugwise/test_config_flow.py

Also, implement fixes for feedback from Core PR https://github.com/home-assistant/core/pull/72450

Adapt to plugwise v0.19.0, update relevant test assert.

---

README.md
custom_components/plugwise/manifest.json

Adding support for the Aqara Plug

Update plugwise to v0.20.0

---

README.md
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/coordinator.py
custom_components/plugwise/entity.py
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
custom_components/plugwise/number.py
custom_components/plugwise/select.py
scripts/core-testing.sh
tests/components/plugwise/fixtures/anna_heatpump_heating/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_cooling/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_idle/all_data.json
tests/components/plugwise/test_climate.py
tests/components/plugwise/test_config_flow.py
tests/components/plugwise/test_init.py

All changes (planned version: v0.27.0:
- Implement https://github.com/home-assistant/core/pull/75109 via plugwise v0.21.1 - https://github.com/plugwise/python-plugwise/releases/tag/v0.21.1
- Implement https://github.com/home-assistant/core/pull/75161
- Climate:  implementing the new Climate classes `ClimateEntityFeature`,  `HVACAction`, and `HVACMode`.
- Climate: fix bug in `hvac_modes` determination, implement changes from plugwise v0.21.1
- Climate: `async_set_temperature()`: support `hvac_mode`-change
- Refresh test fixtures
- Adapt tests/asserts
- Adapt to recent DUC changes wrt error handling
- DUC: provide a single error-message (platinum requirement) when the connection is lost (a single return-message is not needed, provided by the DUC)
- Fix cooldown-interval is None at init, …

Follow Core Plugwise updates II

---

README.md
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
tests/components/plugwise/conftest.py
tests/components/plugwise/fixtures/adam_multiple_devices_per_zone/all_data.json
tests/components/plugwise/fixtures/anna_heatpump_heating/all_data.json
tests/components/plugwise/fixtures/m_adam_cooling/all_data.json
tests/components/plugwise/fixtures/m_adam_heating/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_cooling/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_idle/all_data.json
tests/components/plugwise/fixtures/p1v3_full_option/all_data.json
tests/components/plugwise/fixtures/stretch_v31/all_data.json
tests/components/plugwise/test_diagnostics.py

Also: update/streamline device names and models.

P1: change to two devices: gateway and smartmeter

---

README.md
custom_components/plugwise/entity.py
custom_components/plugwise/gateway.py
custom_components/plugwise/manifest.json
tests/components/plugwise/fixtures/adam_multiple_devices_per_zone/all_data.json
tests/components/plugwise/fixtures/anna_heatpump_heating/all_data.json
tests/components/plugwise/fixtures/m_adam_cooling/all_data.json
tests/components/plugwise/fixtures/m_adam_heating/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_cooling/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_idle/all_data.json
tests/components/plugwise/fixtures/p1v3_full_option/all_data.json
tests/components/plugwise/fixtures/stretch_v31/all_data.json
tests/components/plugwise/test_diagnostics.py

All changes:
- Non-legacy Smiles: introduce device availability
- Adam: Re-add vacation-preset (following recent change in the Plugwise App)
- Link to Plugwise v0.23.0

Introduce device availability

---

README.md
custom_components/plugwise/manifest.json

Fixing https://github.com/home-assistant/core/issues/79708

Bugfix via plugwise v0.24.1

---

scripts/core-testing.sh

This fixes the reported test-fail:

Fix test failing

---

scripts/core-testing.sh

This was what I was looking for :)

Pytest: set logging-level to DEBUG

---

CHANGELOG.md
custom_components/plugwise/util.py
scripts/core-testing.sh
tests/components/plugwise/conftest.py
tests/components/plugwise/test_config_flow.py
tests/components/plugwise/test_init.py

As per Core 86775 followed by 89863 - and via #366

Replace flake8 with ruff

---

renovate.json

Mimic default dependabot behaviour by appending appropriate labels

Add labels

---

CHANGELOG.md
custom_components/plugwise/manifest.json

Version bump to release 0.40.1 formally

Version bump for release

---

renovate.json

Renovatebot Labeling

---

custom_components/plugwise/coordinator.py

I was working on pw-beta, adding the recent Core Plugwise update, I noticed the previous update resulted in a mypy-error in my local testing. The new line works in my local testing.

Improve data-init

---

.prettierignore
CHANGELOG.md
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/manifest.json
custom_components/plugwise/models.py
custom_components/plugwise/number.py
custom_components/plugwise/select.py
custom_components/plugwise/sensor.py
custom_components/plugwise/strings.json
custom_components/plugwise/switch.py
custom_components/plugwise/translations/en.json
custom_components/plugwise/translations/nl.json

binary_sensor / sensor / switch adjusted accordingly, select reads from DeviceData directly (so does number, but with specific key-lookup).
Also number and select updated, and walrus added to sensor.

Alternate approach

---

.github/release.yml

Mimicing what we did with the module in https://github.com/plugwise/python-plugwise/pull/348

Release drafter

---

custom_components/plugwise/models.py
custom_components/plugwise/number.py
custom_components/plugwise/select.py

And follow the approved method from number.py in select.py as well.

Implement Core PR's #95240, #93416

---

CHANGELOG.md
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/manifest.json
custom_components/plugwise/models.py
custom_components/plugwise/number.py
custom_components/plugwise/select.py
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py
tests/components/plugwise/fixtures/anna_heatpump_heating/all_data.json
tests/components/plugwise/test_sensor.py

Following https://github.com/plugwise/python-plugwise/pull/359

Improvements from upstream, bump plugwise to v0.31.8

---

CHANGELOG.md
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/number.py
custom_components/plugwise/select.py
custom_components/plugwise/sensor.py
custom_components/plugwise/switch.py

This fixes the DEBUG-messages with `UndefinedType._singleton`s for Number and Select.

Fix logging, line up for all platforms

---

.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
custom_components/plugwise/__init__.py
custom_components/plugwise/binary_sensor.py
custom_components/plugwise/climate.py
custom_components/plugwise/config_flow.py
custom_components/plugwise/const.py
custom_components/plugwise/entity.py
custom_components/plugwise/number.py
custom_components/plugwise/select.py
custom_components/plugwise/sensor.py
custom_components/plugwise/strings.json
custom_components/plugwise/switch.py
scripts/core-testing.sh

More lining up with Core Plugwise

Further lining up with Core Plugwise

---

.github/workflows/test.yml

Attempt to check why #460 fails

Manually fix version

---

scripts/core-testing.sh

Add snapshot-updating

---

CHANGELOG.md
custom_components/plugwise/climate.py
custom_components/plugwise/manifest.json
custom_components/plugwise/util.py
tests/components/plugwise/fixtures/m_adam_cooling/all_data.json
tests/components/plugwise/fixtures/m_adam_heating/all_data.json
tests/components/plugwise/test_climate.py
tests/components/plugwise/test_select.py

Will only be active for the Adam.

Implement support for mode off

---

CHANGELOG.md
custom_components/plugwise/manifest.json
tests/components/plugwise/fixtures/anna_heatpump_heating/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_cooling/all_data.json
tests/components/plugwise/fixtures/m_anna_heatpump_idle/all_data.json
tests/components/plugwise/test_climate.py
tests/components/plugwise/test_init.py

Implement Anna+Elga backend-update for Issue #512

---

custom_components/plugwise/const.py
custom_components/plugwise/number.py
custom_components/plugwise/select.py

Move some typing-constants from the backend to the HA integration

Move/add Number and Select typing-constants

---

.github/workflows/core_next.yml
.github/workflows/test.yml
.gitignore
custom_components/plugwise/config_flow.py
scripts/core-testing.sh

This looks better, still needs

Actions to py312

---

.github/workflows/core_next.yml
.github/workflows/test.yml
.gitignore
custom_components/plugwise/sensor.py
scripts/core-testing.sh
scripts/python-venv.sh
scripts/setup.sh

Seems promising, needs more tinkering (i.e. suddenly breaks test)
This is branched from #609 with deliberrate higher cache version

Attempt at uv over pip

---

custom_components/plugwise/manifest.json
custom_components/plugwise/number.py
tests/components/plugwise/test_number.py

Implement `@plugwise_command` for the Number platform

---

CHANGELOG.md
custom_components/plugwise/manifest.json
custom_components/plugwise/select.py

Also added to Core: https://github.com/home-assistant/core/pull/117655

Fix for Core Issue #117542

---

.github/workflows/test.yml

Tnx @coderabbitai for your review in #790 :)

No pre-commit on main branch
